### ISSUE TITLE
[Meeting] IOTA Experience Team Smart Contracts Kickoff Meeting 2021-02-16

### ISSUE THREAD

**Issue by antonionardella** [iota-community/IOTA-eXperience-Team#15]
# Time
**UTC** Tue 16-Feb-2021 18:00 (06:00 PM):

Timezone | Date/Time
-- | --
US / Pacific | Tue 16-Feb-2021 11:00 (11:00 AM)
US / Mountain | Tue 16-Feb-2021 12:00 (12:00 AM)
US / Central | Tue 16-Feb-2021 13:00 (1:00 PM)
US / Eastern | Tue 16-Feb-2021 14:00 (2:00 PM)
London | Tue 16-Feb-2021 19:00 (07:00 PM)
Amsterdam | Tue 16-Feb-2021 20:00 (08:00 PM)
Moscow | Tue 16-Feb-2021 21:00 (09:00 PM)
Chennai | Tue 16-Feb-2021 23:30 (11:30 PM)
Hangzhou | Wed 17-Feb-2021 02:00 (02:00 AM)
Tokyo | Wed 17-Feb-2021 03:00 (03:00 AM)
Sydney | Wed 17-Feb-2021 05:00 (05:00 AM)

Or in your local time:

* http://www.timeanddate.com/worldclock/fixedtime.html?msg=2021-02-16&iso=20210216T18
* https://www.wolframalpha.com/input/?i=06PM+UTC%2C+Feb+16%2C+2021+in+local+time

# Links

Meeting Minutes:: < Insert hackmd.io Link >

# Agenda

Kick Off Meeting
- IOTA Experience Team Presentation - Antonio Nardella
- Smart Contracts Introduction - Evaldas Drasutis
- IOTA Smart Contracts X-Team Goals proposal - Evaldas Drasutis
- Q&A

# Invited

* All IOTA community members

## Observers/Guests

Attend the meeting as a guest by calling in to Jitsi, using the links below. If you will be attending as a guest, please comment on this issue to let us know you'll be joining.
_YouTube stream will follow_

# Notes

The agenda comes from issues labelled with xt-agenda across all of the IOTA Experience Team repositories in the iota-community org. Please label any additional issues that should be on the agenda before the meeting starts.

# Joining the meeting

* Link for participants: https://meet.jit.si/ISCP_XTeam
* Stream: https://www.youtube.com/watch?v=dQN0iTH4qkg

# Invitees

Please use the following emoji reactions in this post to indicate your
availability.

* :+1: - Attending
* :-1: - Not attending
* :confused: - Not sure yet

**Comment by AdamCroply** [comment]
Just a shout to let you know I'm interested in attending as guest

**Comment by pasrom** [comment]
I'm interested and planning to attend as guest.

**Comment by TheRicci** [comment]
i will attend as guest

**Comment by JamaleBP** [comment]
I will be attending as a guest!!!

**Comment by NiC0x36** [comment]
I will join as guest too! :)

**Comment by Dries-Vandenneucker** [comment]
No stream?

**Comment by antonionardella** [comment]
Link for participants:
https://meet.jit.si/ISCP_XTeam

Given the expected high influx of people the
