### ISSUE TITLE
[Application]

### ISSUE THREAD

**Issue by DanishSinghSethi** [iota-community/IOTA-eXperience-Team#25]
# X-Team Initiative Application

## Whats your Discord Handle
- Ein Delfin#5171

## I want to participate as
- Developer

## What are you skills? (Programming languages and/or other tools)
Please arrange your skills along with experience.
1. HTML/CSS/JS (2 years)
2. jQuery (1 year)
3. ReactJS (2 months)
4. C++ (3 years)
5. Python (2 years)

## Describe yourself in a few sentences
- I am a high school student with a passion for programming. I've been programming for 5 years and want to use it to create impact.

## Why do you like to join the Identity X-Team? 
- I am working on the Identity Suite Project for Digital Identity as a frontend developer and would love to interact with other developers to gain exposure and support.

**Comment by antonionardella** [comment]
Welcome!
