### ISSUE TITLE
[Application]

### ISSUE THREAD

**Issue by rbrtbrnschn** [iota-community/IOTA-eXperience-Team#26]
# X-Team Initiative Application

## Whats your Discord Handle
- @rbrtbrnschn#0303

## I want to participate as
- [x] Developer
- [ ] Designer
- [ ] Tester
- [ ] Writer

## What are you skills? (Programming languages and/or other tools)
Please arrange your skills along with experience.
1. proficcient in MERN Stack
2. decent with mysql(mariadb)
3. experience in ruby, python3, java, flutter/dart etc.
4. love bash and scripting

## Describe yourself in a few sentene
- dev through and through 
- studying computer sciences in Dresden, Germany
- been coding for 2 years now (22 y/o)

## Why do you like to join the Identity X-Team? 
- Currently working as lead front end dev for the identity project lead by Adam Eunson.

**Comment by antonionardella** [comment]
Welcome!
