### ISSUE TITLE
[Application]

### ISSUE THREAD

**Issue by dumdave** [iota-community/iota-experience-team#35]
# X-Team Initiative Application

## I want to participate as
- [ ] Developer
- [ ] Designer
- [x] Tester
- [x] Writer

## What are you skills? (Programming languages and/or other tools)
Please arrange your skills along with experience.
Good at quickly picking up most languages sufficiently to install, run, write about (inc Rust, WASM, Go).
Examples the 4 install nodes using SWARM guides
Getting the DID software running in Replit to issue (self service) 20+ DIDs then by me VCs
Nearly getting the new Identity Tools running (give me time)

## Describe yourself in a few sentences
Annoying to people who like to move methodically. Entrepreneurial. Keen to learn anything new and interesting.

## Why do you like to join the X-Teams? 
Keen to learn anything new and interesting - and with a particular interest in DID for the Web of Trust initiative and beyond.

## What X-Teams would you like to join?
- [ ] Bee
- [ ] Client Libraries
- [ ] GoShimmer
- [ ] IOTA Access
- [x] IOTA Identity
- [ ] IOTA Streams
- [ ] Permanodes
- [ ] Stronghold
- [ ] Smart Contracts (ISCP)
- [ ] Simplify IOTA

**Comment by Phyloiota** [comment]
accepted and included. Welcome to the team!
